openapi: 3.0.1
info:
  title: ARB
  description: Archlinux Remote Build(ing?), I guess
  version: 1.0.0
servers:
- url: http://localhost:8081/
tags:
- name: urls
paths:
  /build/launch:
    post:
      summary: Launches the build of a package
      requestBody:
        description: name of the package to build
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/buildRequest'
        required: true
      responses:
        200:
          description: package was successfully launched
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/requestResponse'
      x-codegen-request-body-name: package
  /build/check/{UUID}:
    get:
      parameters:
      - name: UUID
        in: path
        description: Get the status of a build
        required: true
        schema:
          type: string
      responses:
        200:
          description: package was successfully launched
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/pkg'
  /build/addURL:
    post:
      tags:
      - urls
      requestBody:
        description: Add a file (with its URL) to the database (secret must be valid)
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/addURLRequest'
        required: true
      responses:
        200:
          description: URL was successfully added
          content: {}
      x-codegen-request-body-name: addURLRequest
  /build/getURL/{UUID}:
    get:
      tags:
      - urls
      parameters:
      - name: UUID
        in: path
        description: Get the URL of the files uploaded by a build
        required: true
        schema:
          type: string
      responses:
        200:
          description: URLs array of the different file
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/File'
  /build/complete:
    post:
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                uuid:
                  type: string
                  description: A build's UUID.
                secret:
                  type: string
                  description: A build's secret.
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/requestResponse'
components:
  schemas:
    pkg:
      type: object
      properties:
        ID:
          type: integer
          format: int64
          example: 1
        UUID:
          type: string
          format: string
          example: 592ba1a4-63bf-4d17-902b-660e74bc2fc4
        Name:
          type: string
        Status:
          type: integer
          format: int64
    File:
      type: object
      properties:
        ID:
          type: integer
          format: int64
          example: 1
        UUID:
          type: string
          format: string
          example: 592ba1a4-63bf-4d17-902b-660e74bc2fc4
        URL:
          type: string
    requestResponse:
      type: object
      properties:
        Type:
          type: integer
          format: int64
          example: 200
        UUID:
          type: string
          example: 592ba1a4-63bf-4d17-902b-660e74bc2fc4
        Text:
          type: string
          example: The build is being launched.
    buildRequest:
      type: object
      properties:
        PackageName:
          type: string
    addURLRequest:
      type: object
      properties:
        UUID:
          type: string
          example: 592ba1a4-63bf-4d17-902b-660e74bc2fc4
        URL:
          type: string
          example: http://minio.lan/arb/akmey-bin-12fbfb84-8230-445b-9402-6c1eb4dd9a85/akmey-bin-0.6-1-x86_64.pkg.tar.xz
        Secret:
          type: string
          example: 21d1ca9d7d9739687cdcd70d845fbd80
